
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "/ITStrategy"
url: "https://sara-sabr.github.io/"

# Build settings
markdown: kramdown
include: ["_pages"]
exclude: ["wip-tec", "CONTRIBUTING.md", "cspell.json", "LICENSE", "link-check.js", "package.json", "package-lock.json", "README.md", "node_modules"]

# i18n
description:
  en: Working in the open! Our work in progress, list of reference material and presentations.
  fr: Travailler ouvertement! Nos travaux en cours, liste de documents de références et présentations.
sectionsList:
  en: ["About us", "Strategies", "Done Enough", "Work In Progress", "Archives"]
  fr: ["À propos de nous", "Stratégies", "Assez fait", "Travaux en cours", "Archives"]
docsTitle:
  en: Documents
  fr: Documents
home:
  en: Home
  fr: Accueil
index:
  en: home.html
  fr: accueil.html
language:
  en: English
  fr: Français
strategies:
  en: Strategies
  fr: Stratégies
presentations:
  en: Presentations
  fr: Présentations
pagesAbout:
  en: About us
  fr: À propos de nous
pagesWIP:
  en: Work In Progress
  fr: Travaux en cours
pagesReview:
  en: Under Review
  fr: En révision
pagesArchive:
  en: Archives
  fr: Archives
pagesOther:
  en: Other
  fr: Autre
subtitle:
  en: Enable the strategic value of IT within ESDC by reducing its risks to accelerate business flexibility.
  fr: Favoriser la valeur stratégique des TI au sein de EDSC en réduisant leurs risques afin d'accélérer la flexibilité de l'entreprise.
docVersionNumber:
  en: Document Version
  fr: Version du document
thisPageHasMoved:
  en: "This page has been modified and can now be found at the following link:"
  fr: "Cette page a été modifiée et peut maintenant être trouvée au lien suivant:"
title:
  en: IT Strategy
  fr: Stratégie TI
viewOnGithub:
  en: View on GitHub
  fr: Voir dans GitHub
writtenBy:
  en: Written by
  fr: Écrit par
lastModified:
  en: Last modified
  fr: Dernière modification
blogPosts:
  en: Blog
  fr: Blogue
notice:
  en: All work found on this site are ideas and proposals from the IT Strategy team within ESDC. Content here does not represent the official stance of ESDC nor the Government of Canada at large.
  fr: Tous les travaux présentés sur ce site sont des idées et des propositions de l'équipe de la stratégie informatique de EDSC. Le contenu présenté ici ne représente pas la position officielle de EDSC ni celle du gouvernement du Canada en général.
feedback:
  en: We encourage you to send us feedback on <a class="alert-link" href="https://github.com/sara-sabr/ITStrategy/">GitHub</a> through Issues or Pull Requests, or simply by <a class="alert-link" href="mailto:EDSC.DGIIT.StrategieTI-ITStrategy.IITB.ESDC@hrsdc-rhdcc.gc.ca">email</a>. Look here on <a class="alert-link" href="how-to-contribute.html">how to contribute</a>.
  fr: Nous vous encourageons à nous envoyer de la rétroaction dans <a class="alert-link" href="https://github.com/sara-sabr/ITStrategy/">GitHub</a> par le biais d'Enjeux (Issues) ou de "Pull Requests", ou bien simplement par <a class="alert-link" href="mailto:EDSC.DGIIT.StrategieTI-ITStrategy.IITB.ESDC@hrsdc-rhdcc.gc.ca">courriel</a>. Regardez ici pour savoir <a class="alert-link" href="comment-contribuer.html">comment contribuer</a>.
printPDF:
  en: Printable version
  fr: Version imprimable
printPDFNotes:
  en: with notes
  fr: avec notes
printPDFNotice:
  en: Note that the printable version only works with modern browsers. Internet Explorer is not supported.
  fr: Notez que la version imprimable ne fonctionne qu'avec des navigateurs modernes. Internet Explorer n'est pas supporté.
